import { useEffect, useMemo, useState } from 'react'
import { formatUnits, type Address } from 'viem'
import { deadline3m, errorText, fmt, minOut, parse18 } from '../lib/format'
import { readContract, type ProtocolState } from '../lib/protocol'
import { writeContractTx } from '../lib/write'
import { Badge, Button, Card, Field, Label, MiniStat, Spinner } from './Ui'
import { QueueHead } from './QueueHead'

export function TradePanel({p,address,onRefresh}:{p?:ProtocolState,address?:Address,onRefresh:()=>Promise<void>|void}){
 const [amount,setAmount]=useState('');const[slip,setSlip]=useState(100);const[quote,setQuote]=useState<bigint>();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('')
 const token=useMemo(()=>{try{return parse18(amount)}catch{return 0n}},[amount])
 useEffect(()=>{let alive=true;(async()=>{try{const q=token?await readContract('quoteProtocolSell',[token]):0n;if(alive)setQuote(q)}catch{if(alive)setQuote(undefined)}})();return()=>{alive=false}},[token])
 const floor=quote?minOut(quote,slip):0n
 const priceImpact=token&&p?.curveReserve?Number(token*10_000n/(p.curveReserve+token))/100:0
 async function sell(){if(!address||!token)return;setBusy(true);setMsg('');try{const q=await readContract('quoteProtocolSell',[token]) as bigint;const minMon=minOut(q,slip);await writeContractTx({account:address,functionName:'submitProtocolSell',args:[token,minMon,deadline3m()],label:'Protocol SELL',detail:`${amount} METOK · min ${fmt(minMon,6)} MON`});setMsg('SELL entered the FIFO queue. No approval is required; if the order is stale, exceeds slippage, or is unsafe, METOK is returned automatically.');await onRefresh()}catch(e){setMsg(errorText(e))}finally{setBusy(false)}}
 async function withdraw(){if(!address||!p?.credit)return;setBusy(true);setMsg('');try{await writeContractTx({account:address,functionName:'withdrawMon',label:'Withdraw MON',detail:`${fmt(p.credit,8)} MON credit`});setMsg('MON credit was withdrawn to your wallet.');await onRefresh()}catch(e){setMsg(errorText(e))}finally{setBusy(false)}}
 return <div className="two-col"><Card><div className="section-head"><div><Label>PROTOCOL CURVE</Label><h2>SELL METOK</h2></div><Badge ok>No approve</Badge></div><p className="muted">SELL uses the same FIFO queue as PLAY. The final quote is calculated at settlement; `minMonOut + deadline` returns the tokens instead of accepting adverse execution.</p><Field label="METOK amount"><input value={amount} onChange={(e:any)=>setAmount(e.target.value)} inputMode="decimal" placeholder="0.0"/></Field><div className="amount-shortcuts"><button onClick={()=>p&&setAmount(formatUnits(p.balance,18))}>MAX</button><button onClick={()=>p&&setAmount(formatUnits(p.balance/2n,18))}>50%</button><button onClick={()=>p&&setAmount(formatUnits(p.balance/4n,18))}>25%</button></div><Field label={`Slippage ${slip/100}%`}><input className="range" type="range" min="0" max="500" step="25" value={slip} onChange={(e:any)=>setSlip(Number(e.target.value))}/></Field><div className="quote-grid"><MiniStat label="Quote now" value={`${fmt(quote,8)} MON`}/><MiniStat label="minMonOut" value={`${fmt(floor,8)} MON`}/><MiniStat label="Wallet" value={`${fmt(p?.balance,4)} METOK`}/><MiniStat label="Deadline" value="3 min"/><MiniStat label="Est. curve share" value={`${priceImpact.toFixed(4)}%`}/><MiniStat label="Execution" value="FIFO protected"/></div><Button className="wide primary action-xl" onClick={sell} disabled={busy||!address||!token||token>(p?.balance||0n)}>{busy?<><Spinner/> Processing</>:'SUBMIT SELL'}</Button>{msg&&<div className="notice">{msg}</div>}</Card><div className="stack"><Card><Label>PULL PAYMENT</Label><h3>MON credit</h3><div className="credit-number"><strong>{fmt(p?.credit,8)}</strong><span>MON</span></div><p className="muted">Protocol SELL, refunds, and P2P payouts all create MON credit; the contract does not push MON during the same transaction.</p><Button className="wide secondary" onClick={withdraw} disabled={busy||!address||!p?.credit}>Withdraw MON</Button></Card><Card><Label>FIFO HEAD</Label><QueueHead head={p?.head} canSettle={p?.canSettle}/></Card><Card><Label>CURVE STATE</Label><div className="row-line"><span>Real MON</span><b>{fmt(p?.realMon,4)}</b></div><div className="row-line"><span>Curve METOK</span><b>{fmt(p?.curveReserve,2)}</b></div><div className="row-line"><span>SELL escrow</span><b>{fmt(p?.sellEscrow,2)}</b></div></Card></div></div>
}
